CREATE TABLE PERFIL (
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(40) DEFAULT NULL
);

INSERT INTO PERFIL (ID, DESCRICAO) VALUES
(1, 'ADMINISTRADOR'),
(2, 'USUARIO');

CREATE TABLE CBO (
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(60) NOT NULL,
  ATIVO CHAR(1) DEFAULT NULL
);

INSERT INTO CBO (ID, NOME, ATIVO) VALUES
(1, 'ASSISTENTE SOCIAL', '1'),
(2, 'PSICOLOGO', '1'),
(3, 'PEDAGOGO', '1');

CREATE TABLE UNIDADE (
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(60) NOT NULL,
  ATIVO CHAR(1) DEFAULT NULL
);

INSERT INTO UNIDADE (ID, NOME, ATIVO) VALUES
(1, 'UNIDADE SEDE', '1'),
(2, 'UNIDADE JUREMA', '1'),
(3, 'UNIDADE PLANALTO', '1'),
(4, 'UNIDADE METROPOLE', '1'),
(5, 'UNIDADE MATOES', '1'),
(6, 'UNIDADE CAPUAN', '1'),
(7, 'UNIDADE GRILO', '1');

CREATE TABLE RACA_COR(
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(70) NOT NULL
);

CREATE TABLE TECNICO (
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CBO INT(11) NOT NULL,
  NOME VARCHAR(70) NOT NULL,
  DATA_NASCIMENTO DATETIME NOT NULL,
  SEXO CHAR(1) NOT NULL,
  RACA_COR INT(11),
  ATIVO CHAR(1) DEFAULT NULL,
  DATA_INCLUSAO DATETIME NOT NULL,
  DATA_EXCLUSAO DATETIME NOT NULL,
  FOREIGN KEY (RACA_COR) REFERENCES RACA_COR(ID),
  FOREIGN KEY (CBO) REFERENCES CBO(ID)
);

CREATE TABLE TECNICO_UNIDADE (
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TECNICO INT(11) NOT NULL,
  UNIDADE INT(11) NOT NULL,
  FOREIGN KEY (TECNICO) REFERENCES TECNICO(ID),
  FOREIGN KEY (UNIDADE) REFERENCES UNIDADE(ID)
);


CREATE TABLE USUARIO (
  ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(255) DEFAULT NULL,
  USUARIO VARCHAR(60) DEFAULT NULL,
  SENHA VARCHAR(100) DEFAULT NULL,
  PERFIL INT(11) DEFAULT NULL,
  EMAIL VARCHAR(80) DEFAULT NULL,
  IMAGEM VARCHAR(100) DEFAULT NULL,
  ATIVO ENUM('S','N') DEFAULT NULL,
  FOREIGN KEY (PERFIL) REFERENCES PERFIL(ID)
);
